<?php
/**
 * FloppyOps Lite — Language Strings
 * Detected from browser Accept-Language or config.
 */

$lang = $_SESSION['lang'] ?? (str_starts_with($_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? '', 'de') ? 'de' : 'en');
if (isset($_GET['lang']) && in_array($_GET['lang'], ['de', 'en'])) {
    $lang = $_GET['lang'];
    $_SESSION['lang'] = $lang;
}

$L = [
    'de' => [
        // General
        'cancel' => 'Abbrechen',
        'save' => 'Speichern',
        'delete' => 'Löschen',
        'close' => 'Schließen',
        'show_config' => 'Config anzeigen',
        'loading' => 'Laden...',
        'error' => 'Fehler',
        'success' => 'Erfolgreich',
        'refresh' => 'Aktualisieren',
        'yes_proceed' => 'Ja, fortfahren',
        'install' => 'Installieren',
        'installed' => 'Installiert',
        'not_installed' => 'Nicht installiert',
        'active' => 'Aktiv',
        'inactive' => 'Inaktiv',
        'online' => 'Online',
        'offline' => 'Offline',
        'all' => 'Alle',
        'none' => 'Keine',

        // Login
        'login_title' => 'Anmelden',
        'login_user' => 'Benutzer',
        'login_pass' => 'Passwort',
        'login_btn' => 'Anmelden',
        'login_hint' => 'Anmeldung mit Proxmox VE oder Linux (root) Zugangsdaten',
        'login_error' => 'Benutzername oder Passwort falsch',

        // Tabs
        'tab_dashboard' => 'Dashboard',
        'tab_vms' => 'VMs/CTs',
        'tab_fail2ban' => 'Fail2ban',
        'tab_nginx' => 'Nginx',
        'tab_zfs' => 'ZFS',
        'tab_vpn' => 'VPN',

        // Dashboard
        'hostname' => 'Hostname',
        'uptime' => 'Uptime',
        'cpu_load' => 'CPU Load',
        'memory' => 'Speicher',
        'disk' => 'Disk',
        'jails' => 'Jails',
        'banned_ips' => 'Gebannte IPs',
        'blocked' => 'Aktuell blockiert',
        'nginx_sites' => 'Nginx Sites',
        'active_sites' => 'Aktive Proxy-Sites',

        // VMs/CTs
        'vms_title' => 'VMs & Container',
        'clone' => 'Clone',
        'clone_title' => 'Clone',
        'new_vmid' => 'Neue VMID',
        'name' => 'Name',
        'full_clone' => 'Full Clone',
        'full_clone_desc' => 'Unabhängige Kopie',
        'linked_clone' => 'Linked Clone',
        'linked_clone_desc' => 'Schnell, abhängig',
        'target_storage' => 'Ziel-Storage',
        'like_source' => 'Wie Quelle',
        'description' => 'Beschreibung',
        'hardware' => 'Hardware anpassen',
        'cpu_cores' => 'CPU Cores',
        'ram_mb' => 'RAM (MB)',
        'swap_mb' => 'Swap (MB)',
        'net_disconnect' => 'Netzwerk trennen',
        'start_after_clone' => 'Nach Clone starten',
        'autostart_boot' => 'Autostart (Boot)',
        'clone_start' => 'Clone starten',
        'cloning' => 'Cloning...',
        'clone_from_snap' => 'aus Snapshot clonen',

        // Fail2ban
        'banned' => 'gebannt',
        'failed' => 'fehlgeschlagen',
        'total' => 'Gesamt',
        'bans' => 'Bans',
        'fails' => 'Fails',
        'unban' => 'Entbannen',
        'no_banned' => 'Keine gebannten IPs',
        'config' => 'Config',
        'ban_log' => 'Ban-Log',
        'save_restart' => 'Speichern & Restart',

        // Nginx
        'proxy_sites' => 'Proxy Sites',
        'new_site' => 'Neue Site',
        'reload_nginx' => 'Nginx Reload',
        'domains' => 'Domain(s)',
        'multi_domain_hint' => 'Mehrere Domains mit Komma trennen',
        'target_ip' => 'Ziel-IP',
        'target_port' => 'Port',
        'enable_ws' => 'WebSocket',
        'force_ssl' => 'HTTPS erzwingen',
        'max_upload' => 'Max Upload',
        'proxy_timeout' => 'Timeout',
        'custom_config' => 'Config bearbeiten',
        'enable_ssl' => 'SSL via Let\'s Encrypt aktivieren',
        'dns_hint' => 'Domain muss auf diesen Server zeigen',
        'create_site' => 'Site erstellen',
        'delete_site' => 'Site loeschen',
        'delete_site_confirm' => 'Site wirklich loeschen?',
        'renew_ssl' => 'SSL erneuern',
        'edit' => 'Bearbeiten',
        'nginx_config' => 'Nginx-Konfiguration',
        'save_reload' => 'Speichern & Reload',

        // ZFS
        'zfs_storage' => 'ZFS Storage',
        'pools_datasets' => 'Pools & Datasets',
        'snapshots' => 'Snapshots',
        'auto_snapshots' => 'Auto-Snapshots',
        'dataset' => 'Dataset',
        'used' => 'Belegt',
        'available' => 'Verfügbar',
        'mountpoint' => 'Mountpoint',
        'utilization' => 'Auslastung',
        'create_snapshot' => 'Snapshot erstellen',
        'snapshot_name' => 'Snapshot-Name',
        'rollback' => 'Rollback',
        'rollback_warn' => 'ACHTUNG: Alle neueren Snapshots werden gelöscht!',
        'clone_dataset' => 'Dataset clonen',
        'target_dataset' => 'Ziel-Dataset',
        'newest_first' => 'Neueste zuerst',
        'oldest_first' => 'Älteste zuerst',
        'largest_first' => 'Größte zuerst',
        'name_az' => 'Name A-Z',
        'all_datasets' => 'Alle Datasets',
        'install_auto_snap' => 'Jetzt installieren',
        'per_dataset' => 'Pro Dataset ein-/ausschalten',
        'interval' => 'Intervall',
        'status' => 'Status',
        'keep' => 'Aufbewahren',
        'timespan' => 'Zeitraum',
        'frequent' => 'alle 15 Min',
        'hourly' => 'Stündlich',
        'daily' => 'Täglich',
        'weekly' => 'Wöchentlich',
        'monthly' => 'Monatlich',
        'zfs_not_installed' => 'Nicht installiert',
        'zfs_install_now' => 'Jetzt installieren',
        'zfs_auto_not_installed_desc' => 'zfs-auto-snapshot ist nicht installiert',
        'zfs_installing' => 'Installiere zfs-auto-snapshot...',
        'zfs_installed_msg' => 'zfs-auto-snapshot installiert',
        'retention_range_error' => 'Wert muss zwischen 1-999 liegen',
        'retention_saved' => 'Retention %label% → %keep% Snapshots',
        'no_datasets' => 'Keine Datasets',
        'dataset_name_required' => 'Dataset und Name erforderlich',
        'show_more' => 'weitere anzeigen',
        'unit_min' => 'Min',
        'unit_hours' => 'Std',
        'unit_days' => 'Tage',
        'unit_weeks' => 'Wochen',
        'unit_months' => 'Monate',
        'interval_frequent' => 'alle 15 Min',
        'interval_hourly' => 'Stündlich',
        'interval_daily' => 'Täglich',
        'interval_weekly' => 'Wöchentlich',
        'interval_monthly' => 'Monatlich',
        'auto_snap_enabled' => 'Auto-Snapshot aktiviert',
        'auto_snap_disabled' => 'Auto-Snapshot deaktiviert',
        'snap_deleted' => 'Snapshot gelöscht',
        'off' => 'Aus',

        // VM/Clone
        'vmid_name_required' => 'VMID und Name erforderlich',
        'clone_started' => 'Clone gestartet — warte auf Abschluss...',
        'clone_background' => 'Clone läuft noch im Hintergrund',
        'hw_config_saved' => 'Hardware-Config angepasst',
        'clone_failed' => 'Clone fehlgeschlagen',

        // Nginx
        'domain_ip_required' => 'Domain und IP erforderlich',
        'site_deleted' => 'Site gelöscht',
        'applying_fix' => 'Wende Fix an...',

        // Updates
        'update_failed' => 'Update fehlgeschlagen',
        'updates_installed' => 'Updates installiert',
        'update_success_reload' => 'Update erfolgreich — Seite wird neu geladen',

        // WireGuard
        'vpn_tunnels' => 'VPN Tunnels',
        'new_tunnel' => 'Neuer Tunnel',
        'live_traffic' => 'Live Traffic',
        'step1_title' => 'Schritt 1/3 — Tunnel-Grundlagen',
        'step2_title' => 'Schritt 2/3 — Peer (Gegenstelle)',
        'step3_title' => 'Schritt 3/3 — Vorschau',
        'iface_name' => 'Interface-Name',
        'listen_port' => 'Listen Port',
        'tunnel_ip' => 'Tunnel-IP (dieses Servers)',
        'private_key' => 'Private Key',
        'public_key' => 'Public Key',
        'firewall_rules' => 'Firewall-Regeln (PostUp/PostDown)',
        'ip_forwarding' => 'IP-Forwarding (IPv4 + IPv6)',
        'nat_masq' => 'NAT / Masquerading',
        'fwd_bridge' => 'Forwarding zu Bridge',
        'generated_rules' => 'Generierte Regeln',
        'peer_endpoint' => 'Peer Endpoint',
        'peer_pubkey' => 'Peer Public Key',
        'allowed_ips' => 'Allowed IPs',
        'preshared_key' => 'PresharedKey',
        'keepalive' => 'Keepalive (Sekunden)',
        'auto_start_tunnel' => 'Tunnel nach Erstellung automatisch starten + beim Boot aktivieren',
        'local_config' => 'Lokale Config',
        'remote_config' => 'Remote-Config (für die Gegenstelle)',
        'copy' => 'Kopieren',
        'create_tunnel' => 'Tunnel erstellen',
        'next' => 'Weiter',
        'back' => 'Zurück',
        'preview' => 'Vorschau',
        'add_peer' => 'Peer hinzufügen',
        'remove_peer' => 'Peer entfernen',
        'confirm_remove_peer' => 'Peer wirklich entfernen?',
        'peer_added' => 'Peer hinzugefügt',
        'peer_removed' => 'Peer entfernt',
        'peer_name' => 'Peer-Name',
        'peer_tunnel_ip' => 'Tunnel-IP',
        'peer_dns' => 'DNS',
        'peer_routes' => 'Erlaubte Routen',
        'peer_config' => 'Peer-Config',
        'server_endpoint' => 'Server-Endpoint',
        'copy_config' => 'Config kopiert',
        'copy_script' => 'Script kopiert',
        'setup_script' => 'Setup-Script',
        'setup_script_hint' => 'Script auf der Gegenstelle als root ausführen — installiert WireGuard und richtet den Tunnel ein.',
        'step1of2' => 'Schritt 1 von 2',
        'step2of2' => 'Schritt 2 von 2',
        'iface_saved' => 'Interface gespeichert',
        'config_saved' => 'Config gespeichert',
        'wg_fields_required' => 'Interface, IP und Private Key erforderlich',
        'wg_peer_key_required' => 'Peer Public Key erforderlich',
        'wg_import_required' => 'Interface-Name und Config erforderlich',
        'no_config' => 'Keine Config vorhanden',
        'allowed_ips_required' => 'AllowedIPs erforderlich',
        'peer_updated' => 'Peer aktualisiert',
        'wg_tunnel_fields_required' => 'Tunnel-IP und Public Key erforderlich',

        // Security
        'tab_security' => 'Security',
        'sec_title' => 'Security Check',
        'sec_open_ports' => 'Offene Ports',
        'sec_risky_ports' => 'Riskante Ports',
        'sec_external' => 'Von außen erreichbar',
        'sec_local_only' => 'Nur lokal',
        'sec_pve_firewall' => 'PVE Firewall',
        'sec_fw_rules' => 'Firewall-Regeln',
        'sec_add_rule' => 'Regel hinzufügen',
        'sec_block_port' => 'Port blockieren',
        'sec_block_confirm' => 'Port %d (%s) wirklich blockieren? Der Dienst wird von außen nicht mehr erreichbar sein.',
        'sec_fw_enable' => 'Aktivieren',
        'sec_fw_enable_warn' => 'Vor dem Aktivieren werden automatisch SSH (22) und PVE WebUI (8006) als ACCEPT-Regeln hinzugefügt.',
        'sec_fw_enabled' => 'Aktiv',
        'sec_fw_disabled' => 'Inaktiv',
        'sec_dc_level' => 'Datacenter',
        'sec_node_level' => 'Node',
        'sec_risk_critical' => 'Kritisch',
        'sec_risk_high' => 'Hoch',
        'sec_risk_medium' => 'Mittel',
        'sec_risk_low' => 'Niedrig',
        'sec_no_risks' => 'Keine Risiken gefunden',
        'sec_risks_found' => 'Risiken',
        'sec_score' => 'Security Score',
        'sec_port' => 'Port',
        'sec_service' => 'Dienst',
        'sec_process' => 'Prozess',
        'sec_address' => 'Adresse',
        'sec_risk' => 'Risiko',
        'sec_action' => 'Aktion',
        'sec_rule_type' => 'Richtung',
        'sec_rule_dport' => 'Ziel-Port',
        'sec_rule_source' => 'Quelle',
        'sec_rule_comment' => 'Kommentar',
        'sec_delete_rule' => 'Regel löschen',
        'sec_delete_rule_confirm' => 'Firewall-Regel wirklich löschen?',
        'sec_scanning' => 'Scanne...',
        'sec_no_rules' => 'Keine Regeln vorhanden',
        'sec_safe' => 'Sicher',
        'sec_total_ports' => 'Ports offen',
        'sec_blocked' => 'Blockieren',
        'sec_info' => 'Scannt offene Ports auf diesem Host, zeigt bekannte Risiken und ermöglicht das Verwalten der PVE Firewall. Riskante Ports können per Klick blockiert werden.',
        'sec_default_rules' => 'Standard-Regeln anwenden',
        'sec_default_rules_desc' => 'Erstellt empfohlene Firewall-Regeln: SSH (22), PVE WebUI (8006) und SPICE Proxy (3128) erlauben, riskante Dienste (rpcbind, MySQL, VNC) blockieren. Bestehende Regeln werden nicht verändert.',
        'sec_default_rules_applied' => 'Standard-Regeln wurden erstellt',

        // Firewall Templates
        'fw_templates' => 'Firewall Templates',
        'fw_templates_desc' => 'Vordefinierte Regelsätze für typische Server-Rollen. Template auswählen und per Klick auf eine VM/CT anwenden.',
        'fw_builtin' => 'Standard',
        'fw_custom' => 'Eigene',
        'fw_rules_count' => '%d Regeln',
        'fw_view_rules' => 'Regeln',
        'fw_apply' => 'Anwenden',
        'fw_create_custom' => 'Eigenes Template',
        'fw_create_custom_desc' => 'Neues Template mit eigenen Regeln erstellen',
        'fw_template_name' => 'Template-Name',
        'fw_template_desc' => 'Beschreibung',
        'fw_template_icon' => 'Icon',
        'fw_save_template' => 'Template speichern',
        'fw_delete_template' => 'Template löschen',
        'fw_delete_template_confirm' => 'Eigenes Template wirklich löschen?',
        'fw_template_saved' => 'Template gespeichert',
        'fw_template_deleted' => 'Template gelöscht',
        'fw_apply_to' => 'Anwenden auf',
        'fw_select_vm' => '— VM/CT wählen —',
        'fw_clear_existing' => 'Bestehende Regeln vorher löschen',
        'fw_clear_warn' => 'Alle aktuellen Firewall-Regeln der VM/CT werden entfernt!',
        'fw_applying' => 'Wende Template an...',
        'fw_applied' => 'Template "%s" angewendet (%d Regeln)',
        'fw_vm_firewall' => 'VM/CT Firewall',
        'fw_vm_firewall_desc' => 'Firewall-Status und Regeln pro VM/CT verwalten.',
        'fw_vm_enabled' => 'Aktiv',
        'fw_vm_disabled' => 'Inaktiv',
        'fw_vm_rules' => 'Regeln',
        'fw_vm_no_guests' => 'Keine VMs/CTs vorhanden',
        'fw_vm_enable_confirm' => 'Firewall aktivieren? Policy wird auf DROP gesetzt — nur erlaubte Ports sind erreichbar.',
        'fw_vm_disable_confirm' => 'Firewall wirklich deaktivieren?',
        'fw_add_rule' => 'Regel hinzufügen',
        'fw_proto' => 'Protokoll',
        'fw_macro' => 'Macro',

        // Help
        'tab_help' => 'Hilfe',
        'help_title' => 'Hilfe & Dokumentation',
        'help_search' => 'Suche in der Hilfe...',
        'help_no_results' => 'Keine Treffer gefunden.',

        // SSL Health
        'ssl_health' => 'SSL Health Check',
        'ssl_click_scan' => 'Klicke auf Aktualisieren um alle Nginx-Sites auf DNS, SSL und IPv4/IPv6-Konsistenz zu prüfen.',
        'ssl_scanning' => 'Prüfe SSL-Konfiguration aller Sites...',
        'ssl_all_ok' => 'Alle Sites OK — keine Probleme gefunden.',
        'ssl_issues_found' => '%d Probleme gefunden',
        'ssl_domain' => 'Domain',
        'ssl_dns_v4' => 'DNS (A)',
        'ssl_dns_v6' => 'DNS (AAAA)',
        'ssl_cert' => 'SSL Cert',
        'ssl_cert_match' => 'Cert Match',
        'ssl_v4v6' => 'IPv4/v6',
        'ssl_expiry' => 'Ablauf',
        'ssl_days' => '%d Tage',
        'ssl_fix' => 'Fix',
        'ssl_no_record' => 'Kein Record',
        'ssl_wrong_ip' => 'Falsche IP',
        'ssl_expired' => 'Abgelaufen',
        'ssl_mismatch' => 'Mismatch',
        'ssl_ok' => 'OK',
        'ssl_fix_ipv6only' => 'ipv6only=on entfernen',
        'ssl_fix_ipv6only_desc' => 'Entfernt ipv6only=on aus der Nginx-Config und lädt Nginx neu.',
        'ssl_fixed' => 'Fix angewendet — Nginx neu geladen',

        // Dashboard (JS)
        'since' => 'seit',
        'load_label' => 'Load:',
        'cores' => 'Cores',

        // Updates (JS)
        'system_up_to_date' => 'System ist aktuell',
        'updates_available' => 'Updates verfügbar',
        'sub_active' => 'Subscription aktiv',
        'no_subscription' => 'Keine Subscription',
        'repo_warn_both' => 'Enterprise und No-Subscription gleichzeitig aktiv — kann zu Konflikten führen. Nur eins aktivieren!',
        'repo_warn_no_sub' => 'Enterprise-Repo aktiv ohne Subscription — Updates werden fehlschlagen!',
        'repo_warn_no_enterprise' => 'Subscription vorhanden aber Enterprise-Repo deaktiviert — kein Zugang zu Enterprise-Updates.',
        'repo_warn_none' => 'Kein PVE-Repository aktiv — keine Proxmox-Updates möglich!',
        'other_repos' => 'Weitere Repositories',
        'apt_running' => 'apt dist-upgrade läuft...',
        'no_license' => 'keine Lizenz',
        'caution' => 'Vorsicht',
        'not_configured' => 'nicht eingerichtet',

        // WireGuard (JS)
        'import_btn' => 'Importieren',
        'wg_step1_title' => 'Schritt 1/3 — Tunnel-Grundlagen',
        'wg_step2_title' => 'Schritt 2/3 — Peer (Gegenstelle)',
        'wg_step3_title' => 'Schritt 3/3 — Vorschau',

        // Nginx (JS)
        'ssl_renewing' => 'SSL-Zertifikat wird erneuert...',
        'ssl_renewed' => 'Zertifikat erneuert für',

        // i18n additions
        'checking' => 'Prüfe...',
        'installed_label' => 'Installiert',
        'available_label' => 'Verfügbar',
        'update_method' => 'Update-Methode',
        'check_btn' => 'Prüfen',
        'system_update' => 'System-Update',
        'confirm_install_all' => 'Alle System-Updates jetzt installieren?',
        'app_autoupdate_saved' => 'App Auto-Update gespeichert',
        'app_autoupdate_disabled' => 'App Auto-Update deaktiviert',
        'autoupdate_saved' => 'Auto-Update gespeichert',
        'autoupdate_disabled' => 'Auto-Update deaktiviert',
        'system_auto_update' => 'System Auto-Update',
        'package' => 'Paket',
        'missing' => 'Fehlt',
    ],
    'en' => [
        'cancel' => 'Cancel',
        'save' => 'Save',
        'delete' => 'Delete',
        'close' => 'Close',
        'show_config' => 'Show config',
        'loading' => 'Loading...',
        'error' => 'Error',
        'success' => 'Success',
        'refresh' => 'Refresh',
        'yes_proceed' => 'Yes, proceed',
        'install' => 'Install',
        'installed' => 'Installed',
        'not_installed' => 'Not installed',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'online' => 'Online',
        'offline' => 'Offline',
        'all' => 'All',
        'none' => 'None',

        'login_title' => 'Login',
        'login_user' => 'Username',
        'login_pass' => 'Password',
        'login_btn' => 'Sign in',
        'login_hint' => 'Sign in with Proxmox VE or Linux (root) credentials',
        'login_error' => 'Invalid username or password',

        'tab_dashboard' => 'Dashboard',
        'tab_vms' => 'VMs/CTs',
        'tab_fail2ban' => 'Fail2ban',
        'tab_nginx' => 'Nginx',
        'tab_zfs' => 'ZFS',
        'tab_vpn' => 'VPN',

        'hostname' => 'Hostname',
        'uptime' => 'Uptime',
        'cpu_load' => 'CPU Load',
        'memory' => 'Memory',
        'disk' => 'Disk',
        'jails' => 'Jails',
        'banned_ips' => 'Banned IPs',
        'blocked' => 'Currently blocked',
        'nginx_sites' => 'Nginx Sites',
        'active_sites' => 'Active proxy sites',

        'vms_title' => 'VMs & Containers',
        'clone' => 'Clone',
        'clone_title' => 'Clone',
        'new_vmid' => 'New VMID',
        'name' => 'Name',
        'full_clone' => 'Full Clone',
        'full_clone_desc' => 'Independent copy',
        'linked_clone' => 'Linked Clone',
        'linked_clone_desc' => 'Fast, dependent',
        'target_storage' => 'Target Storage',
        'like_source' => 'Same as source',
        'description' => 'Description',
        'hardware' => 'Adjust hardware',
        'cpu_cores' => 'CPU Cores',
        'ram_mb' => 'RAM (MB)',
        'swap_mb' => 'Swap (MB)',
        'net_disconnect' => 'Disconnect network',
        'start_after_clone' => 'Start after clone',
        'autostart_boot' => 'Autostart (boot)',
        'clone_start' => 'Start clone',
        'cloning' => 'Cloning...',
        'clone_from_snap' => 'clone from snapshot',

        'banned' => 'banned',
        'failed' => 'failed',
        'total' => 'Total',
        'bans' => 'Bans',
        'fails' => 'Fails',
        'unban' => 'Unban',
        'no_banned' => 'No banned IPs',
        'config' => 'Config',
        'ban_log' => 'Ban Log',
        'save_restart' => 'Save & Restart',

        'proxy_sites' => 'Proxy Sites',
        'new_site' => 'New Site',
        'reload_nginx' => 'Reload Nginx',
        'domains' => 'Domain(s)',
        'multi_domain_hint' => 'Separate multiple domains with comma',
        'target_ip' => 'Target IP',
        'target_port' => 'Port',
        'enable_ws' => 'WebSocket',
        'force_ssl' => 'Force HTTPS',
        'max_upload' => 'Max Upload',
        'proxy_timeout' => 'Timeout',
        'custom_config' => 'Edit config',
        'enable_ssl' => 'Enable SSL via Let\'s Encrypt',
        'dns_hint' => 'Domain must point to this server',
        'create_site' => 'Create site',
        'delete_site' => 'Delete site',
        'delete_site_confirm' => 'Really delete this site?',
        'renew_ssl' => 'Renew SSL',
        'edit' => 'Edit',
        'nginx_config' => 'Nginx configuration',
        'save_reload' => 'Save & Reload',

        'zfs_storage' => 'ZFS Storage',
        'pools_datasets' => 'Pools & Datasets',
        'snapshots' => 'Snapshots',
        'auto_snapshots' => 'Auto-Snapshots',
        'dataset' => 'Dataset',
        'used' => 'Used',
        'available' => 'Available',
        'mountpoint' => 'Mountpoint',
        'utilization' => 'Usage',
        'create_snapshot' => 'Create snapshot',
        'snapshot_name' => 'Snapshot name',
        'rollback' => 'Rollback',
        'rollback_warn' => 'WARNING: All newer snapshots will be deleted!',
        'clone_dataset' => 'Clone dataset',
        'target_dataset' => 'Target dataset',
        'newest_first' => 'Newest first',
        'oldest_first' => 'Oldest first',
        'largest_first' => 'Largest first',
        'name_az' => 'Name A-Z',
        'all_datasets' => 'All datasets',
        'install_auto_snap' => 'Install now',
        'per_dataset' => 'Toggle per dataset',
        'interval' => 'Interval',
        'status' => 'Status',
        'keep' => 'Keep',
        'timespan' => 'Timespan',
        'frequent' => 'every 15 min',
        'hourly' => 'Hourly',
        'daily' => 'Daily',
        'weekly' => 'Weekly',
        'monthly' => 'Monthly',
        'zfs_not_installed' => 'Not installed',
        'zfs_install_now' => 'Install now',
        'zfs_auto_not_installed_desc' => 'zfs-auto-snapshot is not installed',
        'zfs_installing' => 'Installing zfs-auto-snapshot...',
        'zfs_installed_msg' => 'zfs-auto-snapshot installed',
        'retention_range_error' => 'Value must be between 1-999',
        'retention_saved' => 'Retention %label% → %keep% snapshots',
        'no_datasets' => 'No datasets',
        'dataset_name_required' => 'Dataset and name required',
        'show_more' => 'show more',
        'unit_min' => 'min',
        'unit_hours' => 'hrs',
        'unit_days' => 'days',
        'unit_weeks' => 'weeks',
        'unit_months' => 'months',
        'interval_frequent' => 'every 15 min',
        'interval_hourly' => 'Hourly',
        'interval_daily' => 'Daily',
        'interval_weekly' => 'Weekly',
        'interval_monthly' => 'Monthly',
        'auto_snap_enabled' => 'Auto-snapshot enabled',
        'auto_snap_disabled' => 'Auto-snapshot disabled',
        'snap_deleted' => 'Snapshot deleted',
        'off' => 'Off',

        // VM/Clone
        'vmid_name_required' => 'VMID and name required',
        'clone_started' => 'Clone started — waiting for completion...',
        'clone_background' => 'Clone is still running in the background',
        'hw_config_saved' => 'Hardware config applied',
        'clone_failed' => 'Clone failed',

        // Nginx
        'domain_ip_required' => 'Domain and IP required',
        'site_deleted' => 'Site deleted',
        'applying_fix' => 'Applying fix...',

        // Updates
        'update_failed' => 'Update failed',
        'updates_installed' => 'Updates installed',
        'update_success_reload' => 'Update successful — page will reload',

        'vpn_tunnels' => 'VPN Tunnels',
        'new_tunnel' => 'New Tunnel',
        'live_traffic' => 'Live Traffic',
        'step1_title' => 'Step 1/3 — Tunnel Basics',
        'step2_title' => 'Step 2/3 — Peer (Remote)',
        'step3_title' => 'Step 3/3 — Preview',
        'iface_name' => 'Interface name',
        'listen_port' => 'Listen port',
        'tunnel_ip' => 'Tunnel IP (this server)',
        'private_key' => 'Private Key',
        'public_key' => 'Public Key',
        'firewall_rules' => 'Firewall rules (PostUp/PostDown)',
        'ip_forwarding' => 'IP Forwarding (IPv4 + IPv6)',
        'nat_masq' => 'NAT / Masquerading',
        'fwd_bridge' => 'Forward to bridge',
        'generated_rules' => 'Generated rules',
        'peer_endpoint' => 'Peer Endpoint',
        'peer_pubkey' => 'Peer Public Key',
        'allowed_ips' => 'Allowed IPs',
        'preshared_key' => 'PresharedKey',
        'keepalive' => 'Keepalive (seconds)',
        'auto_start_tunnel' => 'Start tunnel after creation + enable at boot',
        'local_config' => 'Local config',
        'remote_config' => 'Remote config (for the peer)',
        'copy' => 'Copy',
        'create_tunnel' => 'Create tunnel',
        'next' => 'Next',
        'back' => 'Back',
        'preview' => 'Preview',
        'add_peer' => 'Add peer',
        'remove_peer' => 'Remove peer',
        'confirm_remove_peer' => 'Really remove this peer?',
        'peer_added' => 'Peer added',
        'peer_removed' => 'Peer removed',
        'peer_name' => 'Peer name',
        'peer_tunnel_ip' => 'Tunnel IP',
        'peer_dns' => 'DNS',
        'peer_routes' => 'Allowed routes',
        'peer_config' => 'Peer config',
        'server_endpoint' => 'Server endpoint',
        'copy_config' => 'Config copied',
        'copy_script' => 'Script copied',
        'setup_script' => 'Setup script',
        'setup_script_hint' => 'Run this script as root on the remote side — installs WireGuard and sets up the tunnel.',
        'step1of2' => 'Step 1 of 2',
        'step2of2' => 'Step 2 of 2',
        'iface_saved' => 'Interface saved',
        'config_saved' => 'Config saved',
        'wg_fields_required' => 'Interface, IP and Private Key required',
        'wg_peer_key_required' => 'Peer Public Key required',
        'wg_import_required' => 'Interface name and config required',
        'no_config' => 'No config available',
        'allowed_ips_required' => 'AllowedIPs required',
        'peer_updated' => 'Peer updated',
        'wg_tunnel_fields_required' => 'Tunnel IP and Public Key required',

        // Security
        'tab_security' => 'Security',
        'sec_title' => 'Security Check',
        'sec_open_ports' => 'Open Ports',
        'sec_risky_ports' => 'Risky Ports',
        'sec_external' => 'Externally reachable',
        'sec_local_only' => 'Local only',
        'sec_pve_firewall' => 'PVE Firewall',
        'sec_fw_rules' => 'Firewall Rules',
        'sec_add_rule' => 'Add rule',
        'sec_block_port' => 'Block port',
        'sec_block_confirm' => 'Really block port %d (%s)? The service will no longer be reachable externally.',
        'sec_fw_enable' => 'Enable',
        'sec_fw_enable_warn' => 'Before enabling, SSH (22) and PVE WebUI (8006) ACCEPT rules will be added automatically.',
        'sec_fw_enabled' => 'Active',
        'sec_fw_disabled' => 'Inactive',
        'sec_dc_level' => 'Datacenter',
        'sec_node_level' => 'Node',
        'sec_risk_critical' => 'Critical',
        'sec_risk_high' => 'High',
        'sec_risk_medium' => 'Medium',
        'sec_risk_low' => 'Low',
        'sec_no_risks' => 'No risks found',
        'sec_risks_found' => 'Risks',
        'sec_score' => 'Security Score',
        'sec_port' => 'Port',
        'sec_service' => 'Service',
        'sec_process' => 'Process',
        'sec_address' => 'Address',
        'sec_risk' => 'Risk',
        'sec_action' => 'Action',
        'sec_rule_type' => 'Direction',
        'sec_rule_dport' => 'Dest. Port',
        'sec_rule_source' => 'Source',
        'sec_rule_comment' => 'Comment',
        'sec_delete_rule' => 'Delete rule',
        'sec_delete_rule_confirm' => 'Really delete this firewall rule?',
        'sec_scanning' => 'Scanning...',
        'sec_no_rules' => 'No rules configured',
        'sec_safe' => 'Safe',
        'sec_total_ports' => 'Ports open',
        'sec_blocked' => 'Block',
        'sec_info' => 'Scans open ports on this host, highlights known risks and lets you manage the PVE Firewall. Risky ports can be blocked with one click.',
        'sec_default_rules' => 'Apply default rules',
        'sec_default_rules_desc' => 'Creates recommended firewall rules: Allow SSH (22), PVE WebUI (8006) and SPICE Proxy (3128), block risky services (rpcbind, MySQL, VNC). Existing rules are not modified.',
        'sec_default_rules_applied' => 'Default rules have been applied',

        // Firewall Templates
        'fw_templates' => 'Firewall Templates',
        'fw_templates_desc' => 'Predefined rule sets for common server roles. Select a template and apply it to a VM/CT with one click.',
        'fw_builtin' => 'Built-in',
        'fw_custom' => 'Custom',
        'fw_rules_count' => '%d rules',
        'fw_view_rules' => 'Rules',
        'fw_apply' => 'Apply',
        'fw_create_custom' => 'Custom Template',
        'fw_create_custom_desc' => 'Create a new template with custom rules',
        'fw_template_name' => 'Template name',
        'fw_template_desc' => 'Description',
        'fw_template_icon' => 'Icon',
        'fw_save_template' => 'Save template',
        'fw_delete_template' => 'Delete template',
        'fw_delete_template_confirm' => 'Really delete this custom template?',
        'fw_template_saved' => 'Template saved',
        'fw_template_deleted' => 'Template deleted',
        'fw_apply_to' => 'Apply to',
        'fw_select_vm' => '— Select VM/CT —',
        'fw_clear_existing' => 'Clear existing rules first',
        'fw_clear_warn' => 'All current firewall rules of the VM/CT will be removed!',
        'fw_applying' => 'Applying template...',
        'fw_applied' => 'Template "%s" applied (%d rules)',
        'fw_vm_firewall' => 'VM/CT Firewall',
        'fw_vm_firewall_desc' => 'Manage firewall status and rules per VM/CT.',
        'fw_vm_enabled' => 'Active',
        'fw_vm_disabled' => 'Inactive',
        'fw_vm_rules' => 'Rules',
        'fw_vm_no_guests' => 'No VMs/CTs found',
        'fw_vm_enable_confirm' => 'Enable firewall? Policy will be set to DROP — only allowed ports will be reachable.',
        'fw_vm_disable_confirm' => 'Really disable firewall?',
        'fw_add_rule' => 'Add rule',
        'fw_proto' => 'Protocol',
        'fw_macro' => 'Macro',

        // Help
        'tab_help' => 'Help',
        'help_title' => 'Help & Documentation',
        'help_search' => 'Search help...',
        'help_no_results' => 'No results found.',

        // SSL Health
        'ssl_health' => 'SSL Health Check',
        'ssl_click_scan' => 'Click Refresh to check all Nginx sites for DNS, SSL and IPv4/IPv6 consistency.',
        'ssl_scanning' => 'Checking SSL configuration of all sites...',
        'ssl_all_ok' => 'All sites OK — no issues found.',
        'ssl_issues_found' => '%d issues found',
        'ssl_domain' => 'Domain',
        'ssl_dns_v4' => 'DNS (A)',
        'ssl_dns_v6' => 'DNS (AAAA)',
        'ssl_cert' => 'SSL Cert',
        'ssl_cert_match' => 'Cert Match',
        'ssl_v4v6' => 'IPv4/v6',
        'ssl_expiry' => 'Expiry',
        'ssl_days' => '%d days',
        'ssl_fix' => 'Fix',
        'ssl_no_record' => 'No record',
        'ssl_wrong_ip' => 'Wrong IP',
        'ssl_expired' => 'Expired',
        'ssl_mismatch' => 'Mismatch',
        'ssl_ok' => 'OK',
        'ssl_fix_ipv6only' => 'Remove ipv6only=on',
        'ssl_fix_ipv6only_desc' => 'Removes ipv6only=on from Nginx config and reloads Nginx.',
        'ssl_fixed' => 'Fix applied — Nginx reloaded',

        // Dashboard (JS)
        'since' => 'since',
        'load_label' => 'Load:',
        'cores' => 'Cores',

        // Updates (JS)
        'system_up_to_date' => 'System is up to date',
        'updates_available' => 'updates available',
        'sub_active' => 'Subscription active',
        'no_subscription' => 'No Subscription',
        'repo_warn_both' => 'Enterprise and No-Subscription both active — may cause conflicts. Enable only one!',
        'repo_warn_no_sub' => 'Enterprise repo active without subscription — updates will fail!',
        'repo_warn_no_enterprise' => 'Subscription present but Enterprise repo disabled — no access to enterprise updates.',
        'repo_warn_none' => 'No PVE repository active — no Proxmox updates possible!',
        'other_repos' => 'Other Repositories',
        'apt_running' => 'apt dist-upgrade running...',
        'no_license' => 'no license',
        'caution' => 'Caution',
        'not_configured' => 'not configured',

        // WireGuard (JS)
        'import_btn' => 'Import',
        'wg_step1_title' => 'Step 1/3 — Tunnel Basics',
        'wg_step2_title' => 'Step 2/3 — Peer (Remote Side)',
        'wg_step3_title' => 'Step 3/3 — Preview',

        // Nginx (JS)
        'ssl_renewing' => 'Renewing SSL certificate...',
        'ssl_renewed' => 'Certificate renewed for',

        // i18n additions
        'checking' => 'Checking...',
        'installed_label' => 'Installed',
        'available_label' => 'Available',
        'update_method' => 'Update method',
        'check_btn' => 'Check',
        'system_update' => 'System Update',
        'confirm_install_all' => 'Install all system updates now?',
        'app_autoupdate_saved' => 'App auto-update saved',
        'app_autoupdate_disabled' => 'App auto-update disabled',
        'autoupdate_saved' => 'Auto-update saved',
        'autoupdate_disabled' => 'Auto-update disabled',
        'system_auto_update' => 'System Auto-Update',
        'package' => 'Package',
        'missing' => 'Missing',
    ],
];

$t = $L[$lang] ?? $L['de'];
function __($key) {
    global $t;
    return $t[$key] ?? $key;
}


